[package]
name = "border-explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["std"] }
memchr = "2.7.5"
serde = { version = "1.0.219", features = ["std", "derive"], default-features = false }
serde_json = "1.0.140"
